### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GregTexas** [MennovH/HomeAssistant#5]
I did a fresh install and I get this: curl: (7) Failed to connect to supervisor port 80 after 0 ms: Couldn't connect to server
[08:40:41] ERROR: Something went wrong contacting the API
TokenRemover will run only once due to invalid recurrence configuration

**Comment by MennovH** [comment]
Hi GregTexas,

Thanks for reporting the problem.
I was able to reproduce it, but I haven't got the time to fix it the way I wanted.
For now, I have disabled AppArmor as this was a quick fix.
Please let me know if this resolves the problem.

Thanks in advance!
